### ISSUE TITLE
Remove openai from requirements.txt

### ISSUE THREAD

**Issue by a-mufasa** [KalaRohit/Google-AI-Hackathon#57]
Remove `openai` from requirements.txt!
![image](https://github.com/KalaRohit/Google-AI-Hackathon/assets/90020418/c8c773b5-fdbb-40f1-8304-4d13a14aad8f)

**Comment by a-mufasa** [comment]
Thank you good sir. And thanks for lending me your Lamborghini the other day 🙏🙏

**Comment by KalaRohit** [comment]
No prob @a-mufasa
