### ISSUE TITLE
Revert diagram once again

### ISSUE THREAD

**Issue by a-mufasa** [KalaRohit/Google-AI-Hackathon#64]
Hello again. Good work so far today man! Is there something weird about these arrows or is it just me?
![image](https://github.com/KalaRohit/Google-AI-Hackathon/assets/90020418/9272c96b-814f-4b7f-8222-5488394a3ebe)
![image](https://github.com/KalaRohit/Google-AI-Hackathon/assets/90020418/985980d7-2e25-4875-9bf6-bdec8a9748c1)

**Comment by KalaRohit** [comment]
What do you want from me...

**Comment by KalaRohit** [comment]
lgtm 👍

**Comment by a-mufasa** [comment]
@zoeingwingkei what is your opinion? I don't believe @KalaRohit is familiar with UI...

**Comment by a-mufasa** [comment]
![image](https://github.com/KalaRohit/Google-AI-Hackathon/assets/90020418/db58aa30-b40a-42bc-bf84-dfa3a1e9944c)

I took another look at it with an investigative eye. It appears these are not aligned 😕

**Comment by KalaRohit** [comment]
known bug, our engineers are on it

**Comment by zoeingwingkei** [comment]
> @zoeingwingkei what is your opinion? I don't believe @KalaRohit is familiar with UI...

That's fine... I don't think any designers will look at that image, that's only for devs ☕️

**Comment by a-mufasa** [comment]
![image](https://github.com/KalaRohit/Google-AI-Hackathon/assets/90020418/10bcec31-ac7a-43a7-9819-c97ad11932c9)

sounds good boss!
